version: "3.7"
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:${NGINX_WEB_PORT:-80}:80"
    depends_on:
      - app
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
        PM2_CONFIG: ${PM2_CONFIG:-pm2.json}
    image: "laravel_app_${PREFIX:-dev}"
    restart: always
    mem_limit: 24g
    ports:
      - 127.0.0.1::9000
    volumes:
      - ./app:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "127.0.0.1::6379"
    networks:
      - default
    volumes:
      - "redis:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      timeout: 5s
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
    ports:
      - "127.0.0.1:${DB_PORT:-3306}:3306"
    networks:
      - default
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  default:

volumes:
  redis:
  dbdata:
